import type { Project } from '../types';

export function formatDate(date: string): string {
  return new Date(date).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
}

export function formatRelativeTime(date: string): string {
  const now = new Date();
  const past = new Date(date);
  const diffMs = now.getTime() - past.getTime();
  if (diffMs < 0) return 'just now';
  const diffMins = Math.floor(diffMs / 60000);
  const diffHours = Math.floor(diffMs / 3600000);
  const diffDays = Math.floor(diffMs / 86400000);

  if (diffMins < 1) return 'just now';
  if (diffMins < 60) return `${diffMins}m ago`;
  if (diffHours < 24) return `${diffHours}h ago`;
  if (diffDays < 7) return `${diffDays}d ago`;
  return formatDate(date);
}

export function exportMarkdown(project: Project): string {
  const bp = project.blueprint;
  let md = `# ${bp.projectOverview.name}\n\n`;
  md += `> ${bp.projectOverview.tagline}\n\n`;
  md += `## Project Overview\n\n${bp.projectOverview.description}\n\n`;
  md += `**Target Audience:** ${bp.projectOverview.targetAudience}\n\n`;
  if (bp.projectOverview.tags?.length) {
    md += `**Tags:** ${bp.projectOverview.tags.join(', ')}\n\n`;
  }

  md += `## Tech Stack\n\n| Category | Technology | Reason |\n|----------|-----------|--------|\n`;
  bp.techStack.forEach(t => { md += `| ${t.category} | ${t.technology} | ${t.reason} |\n`; });
  md += '\n';

  md += `## Architecture\n\n${bp.architecture.description}\n\n`;
  md += `### Components\n\n`;
  bp.architecture.components.forEach(c => {
    md += `#### ${c.name}\n- **Responsibility:** ${c.responsibility}\n- **Connections:** ${c.connections.join(', ')}\n\n`;
  });
  md += `**Data Flow:** ${bp.architecture.dataFlow}\n\n`;

  md += `## Database Schema\n\n`;
  bp.databaseSchema.forEach(t => {
    md += `### ${t.table}\n| Column | Type | Constraints |\n|--------|------|-------------|\n`;
    t.columns.forEach(c => { md += `| ${c.name} | ${c.type} | ${c.constraints} |\n`; });
    md += `**Relationships:** ${t.relationships}\n\n`;
  });

  md += `## API Endpoints\n\n| Method | Path | Description |\n|--------|------|-------------|\n`;
  bp.apiEndpoints.forEach(e => { md += `| ${e.method} | ${e.path} | ${e.description} |\n`; });
  md += '\n';

  md += `## Folder Structure\n\n`;
  bp.folderStructure.forEach(f => { md += `- \`${f.path}\` — ${f.description}\n`; });
  md += '\n';

  md += `## Development Roadmap\n\n`;
  bp.developmentRoadmap.forEach(p => {
    md += `### ${p.phase} (${p.duration})\n**Goals:**\n${p.goals.map(g => `- ${g}`).join('\n')}\n\n**Deliverables:**\n${p.deliverables.map(d => `- ${d}`).join('\n')}\n\n`;
  });

  md += `## UI Pages\n\n`;
  bp.uiPages.forEach(p => {
    md += `### ${p.name}\n**Purpose:** ${p.purpose}\n**Components:** ${p.components.join(', ')}\n**Wireframe:** ${p.wireframe}\n\n`;
  });

  md += `## Sprint Plan\n\n`;
  bp.sprintPlan.forEach(s => {
    md += `### ${s.sprint} (${s.duration})\n**Goal:** ${s.goal}\n**Tasks:**\n${s.tasks.map(t => `- ${t}`).join('\n')}\n\n`;
  });

  md += `## README\n\n\`\`\`markdown\n${bp.readme}\n\`\`\`\n\n`;

  md += `## Deployment Guide\n\n`;
  bp.deploymentGuide.forEach(d => {
    md += `### ${d.step}\n**Platform:** ${d.platform}\n${d.instructions}\n`;
    if (d.commands.length) md += `\n\`\`\`bash\n${d.commands.join('\n')}\n\`\`\`\n`;
    md += '\n';
  });

  md += `## Testing Strategy\n\n`;
  md += `- **Unit:** ${bp.testingStrategy.unit}\n- **Integration:** ${bp.testingStrategy.integration}\n- **E2E:** ${bp.testingStrategy.e2e}\n- **Performance:** ${bp.testingStrategy.performance}\n- **Tools:** ${bp.testingStrategy.tools.join(', ')}\n\n`;

  md += `## Cost Estimation\n\n| Resource | Monthly Cost | Notes |\n|----------|-------------|-------|\n`;
  bp.costEstimation.forEach(c => { md += `| ${c.resource} | ${c.monthlyCost} | ${c.notes} |\n`; });
  md += '\n';

  md += `## Future Enhancements\n\n`;
  bp.futureEnhancements.forEach(e => {
    md += `### ${e.feature} (${e.priority})\n${e.description}\n\n`;
  });

  md += `---\n\n*Generated by ProjectPilot AI on ${formatDate(project.created_at)}*\n`;
  return md;
}

export function downloadFile(filename: string, content: string, mimeType = 'text/plain') {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function exportPDF(project: Project): boolean {
  const bp = project.blueprint;
  const win = window.open('', '_blank');
  if (!win) return false;
  win.document.write(`
    <html><head><title>${escapeHtml(bp.projectOverview.name)} — Blueprint</title>
    <style>
      body { font-family: Inter, sans-serif; max-width: 800px; margin: 40px auto; padding: 20px; color: #1f2937; line-height: 1.6; }
      h1 { color: #2563eb; border-bottom: 2px solid #e5e7eb; padding-bottom: 10px; }
      h2 { color: #1e40af; margin-top: 32px; }
      h3 { color: #374151; }
      table { width: 100%; border-collapse: collapse; margin: 12px 0; }
      th, td { border: 1px solid #e5e7eb; padding: 8px 12px; text-align: left; font-size: 14px; }
      th { background: #f9fafb; font-weight: 600; }
      code, pre { background: #f3f4f6; padding: 2px 6px; border-radius: 4px; font-family: monospace; font-size: 13px; }
      pre { padding: 16px; overflow-x: auto; }
      blockquote { border-left: 4px solid #2563eb; margin: 16px 0; padding: 8px 16px; background: #eff6ff; }
      ul { margin: 8px 0; padding-left: 24px; }
      p { margin: 8px 0; }
    </style></head><body>
    ${markdownToHTML(exportMarkdown(project))}
    <script>window.onload = () => { window.print(); }</script>
    </body></html>
  `);
  win.document.close();
  return true;
}

function escapeHtml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

function markdownToHTML(md: string): string {
  const escaped = escapeHtml(md);
  const lines = escaped.split('\n');
  let html = '';
  let inList = false;
  let inCodeBlock = false;
  let codeContent = '';

  for (const line of lines) {
    if (line.startsWith('```')) {
      if (inCodeBlock) {
        html += `<pre><code>${codeContent}</code></pre>\n`;
        codeContent = '';
        inCodeBlock = false;
      } else {
        inCodeBlock = true;
      }
      continue;
    }
    if (inCodeBlock) {
      codeContent += line + '\n';
      continue;
    }
    if (line.startsWith('#### ')) {
      if (inList) { html += '</ul>\n'; inList = false; }
      html += `<h4>${line.slice(5)}</h4>\n`;
    } else if (line.startsWith('### ')) {
      if (inList) { html += '</ul>\n'; inList = false; }
      html += `<h3>${line.slice(4)}</h3>\n`;
    } else if (line.startsWith('## ')) {
      if (inList) { html += '</ul>\n'; inList = false; }
      html += `<h2>${line.slice(3)}</h2>\n`;
    } else if (line.startsWith('# ')) {
      if (inList) { html += '</ul>\n'; inList = false; }
      html += `<h1>${line.slice(2)}</h1>\n`;
    } else if (line.startsWith('> ')) {
      if (inList) { html += '</ul>\n'; inList = false; }
      html += `<blockquote>${line.slice(2)}</blockquote>\n`;
    } else if (line.startsWith('- ')) {
      if (!inList) { html += '<ul>\n'; inList = true; }
      html += `<li>${inlineMd(line.slice(2))}</li>\n`;
    } else if (line.trim() === '') {
      if (inList) { html += '</ul>\n'; inList = false; }
      html += '';
    } else if (line.startsWith('|')) {
      if (inList) { html += '</ul>\n'; inList = false; }
      html += `<p>${inlineMd(line)}</p>\n`;
    } else {
      if (inList) { html += '</ul>\n'; inList = false; }
      html += `<p>${inlineMd(line)}</p>\n`;
    }
  }
  if (inList) html += '</ul>\n';
  if (inCodeBlock) html += `<pre><code>${codeContent}</code></pre>\n`;
  return html;
}

function inlineMd(s: string): string {
  return s
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/`(.+?)`/g, '<code>$1</code>');
}
